'use server';
/**
 * @fileOverview An AI assistant that analyzes sales data to provide insights into best-selling products,
 * peak sales periods, and customer purchasing patterns, offering actionable recommendations.
 *
 * - salesPerformanceInsights - A function that handles the sales data analysis process.
 * - SalesPerformanceInsightsInput - The input type for the salesPerformanceInsights function.
 * - SalesPerformanceInsightsOutput - The return type for the salesPerformanceInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SalesPerformanceInsightsInputSchema = z.object({
  businessType: z
    .string()
    .describe('The type of business (e.g., "Shop", "Restaurant", "E-commerce").'),
  salesTransactions: z
    .array(
      z.object({
        transactionId: z.string().describe('Unique identifier for the transaction.'),
        productId: z.string().describe('Unique identifier for the product.'),
        productName: z.string().describe('Name of the product sold.'),
        category: z.string().optional().describe('Category of the product.'),
        quantity: z.number().int().positive().describe('Quantity of the product sold.'),
        unitPrice: z.number().positive().describe('Price per unit of the product.'),
        totalPrice: z.number().positive().describe('Total price for this line item.'),
        timestamp: z
          .string()
          .datetime()
          .describe('ISO 8601 formatted timestamp of the sale.'),
        customerId: z.string().optional().describe('Unique identifier for the customer.'),
        customerName: z.string().optional().describe('Name of the customer.'),
      })
    )
    .describe('An array of historical sales transactions.'),
  productCatalog: z
    .array(
      z.object({
        productId: z.string().describe('Unique identifier for the product.'),
        productName: z.string().describe('Name of the product.'),
        category: z.string().optional().describe('Category of the product.'),
        description: z.string().optional().describe('Description of the product.'),
        currentStock: z.number().int().optional().describe('Current stock level of the product.'),
      })
    )
    .optional()
    .describe('Optional: A list of products with their details.'),
});
export type SalesPerformanceInsightsInput = z.infer<
  typeof SalesPerformanceInsightsInputSchema
>;

const SalesPerformanceInsightsOutputSchema = z.object({
  bestSellingProducts: z
    .array(
      z.object({
        productId: z.string().describe('Unique identifier for the best-selling product.'),
        productName: z.string().describe('Name of the best-selling product.'),
        totalRevenue: z.number().describe('Total revenue generated by this product.'),
        totalQuantitySold: z
          .number()
          .int()
          .describe('Total quantity of this product sold.'),
        insight: z.string().describe('An insight or recommendation for this product.'),
      })
    )
    .describe('A list of products with the highest sales performance.'),
  peakSalesPeriods: z
    .object({
      summary: z
        .string()
        .describe(
          'A summary of the identified peak sales periods (e.g., "Weekends", "Lunch hours", "Holiday season").'
        ),
      detailedPeriods: z
        .array(
          z.object({
            period: z
              .string()
              .describe(
                'Description of the peak period (e.g., "Monday 12-2 PM", "December").'
              ),
            totalRevenue: z.number().describe('Total revenue during this period.'),
            averageRevenuePerDay: z
              .number()
              .optional()
              .describe('Average daily revenue during this period.'),
          })
        )
        .optional()
        .describe('Detailed breakdown of specific peak sales periods.'),
    })
    .describe('Insights into when sales are highest.'),
  customerPurchasingPatterns: z
    .array(
      z.object({
        patternDescription: z
          .string()
          .describe(
            'A description of an identified customer purchasing pattern (e.g., "Customers buying X also buy Y", "Repeat purchases of Z every month").'
          ),
        recommendation: z
          .string()
          .describe('An actionable recommendation based on this pattern.'),
      })
    )
    .describe('Identified customer purchasing behaviors and patterns.'),
  overallSalesStrategyRecommendation: z
    .string()
    .describe('An overall recommendation to optimize sales strategies based on all insights.'),
});
export type SalesPerformanceInsightsOutput = z.infer<
  typeof SalesPerformanceInsightsOutputSchema
>;

export async function salesPerformanceInsights(
  input: SalesPerformanceInsightsInput
): Promise<SalesPerformanceInsightsOutput> {
  return salesPerformanceInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'salesPerformanceInsightsPrompt',
  input: {schema: SalesPerformanceInsightsInputSchema},
  output: {schema: SalesPerformanceInsightsOutputSchema},
  prompt: `You are an AI Sales Performance Analyst for an {{businessType}} business. Your goal is to analyze the provided sales data and generate actionable insights to help the business owner optimize their sales strategies and increase revenue.

Analyze the following sales transactions and product catalog (if provided):

Sales Transactions:
{{{JSON.stringify salesTransactions}}}

{{#if productCatalog}}
Product Catalog:
{{{JSON.stringify productCatalog}}}
{{/if}}

Based on this data, provide the following insights:

1.  **Best-Selling Products**: Identify the top 5-10 products that generate the most revenue and quantity sold. For each, provide a brief insight or recommendation.
2.  **Peak Sales Periods**: Identify specific times (e.g., days of the week, times of day, months, or seasons) when sales are highest. Summarize these periods and provide a detailed breakdown if possible.
3.  **Customer Purchasing Patterns**: Describe any noticeable patterns in how customers purchase products (e.g., frequently bought together, repeat purchases, impact of promotions). Provide actionable recommendations for each pattern.
4.  **Overall Sales Strategy Recommendation**: Based on all insights, provide a concise overall recommendation to optimize sales.

Ensure your output strictly adheres to the SalesPerformanceInsightsOutputSchema. Do not include any conversational text outside of the JSON.`,
});

const salesPerformanceInsightsFlow = ai.defineFlow(
  {
    name: 'salesPerformanceInsightsFlow',
    inputSchema: SalesPerformanceInsightsInputSchema,
    outputSchema: SalesPerformanceInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
